export const ADMIN_ROUTE = '/Admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/'
export const BASKET_ROUTE = '/basket'
export const WEAPON_ROUTE = '/weapon'
export const MAIN_ROUTE = '/main'